using System.Collections.Generic;

public static class SpriteMap
{
    // Relación botón -> nombre sprite TMP
    public static readonly Dictionary<string, string> spriteMap = new Dictionary<string, string>()
    {
        // Keyboard keys
        {"0", "0_Key_Light" },
        {"1", "1_Key_Light" },
        {"2", "2_Key_Light" },
        {"3", "3_Key_Light" },
        {"4", "4_Key_Light" },
        {"5", "5_Key_Light" },
        {"6", "6_Key_Light" },
        {"7", "7_Key_Light" },
        {"8", "8_Key_Light" },
        {"9", "9_Key_Light" },
        {"question mark", "Question_Key_Light" },
        {"f1", "F1_Key_Light" },
        {"f2", "F2_Key_Light" },
        {"f3", "F3_Key_Light" },
        {"f4", "F4_Key_Light" },
        {"f5", "F5_Key_Light" },
        {"f6", "F6_Key_Light" },
        {"f7", "F7_Key_Light" },
        {"f8", "F8_Key_Light" },
        {"f9", "F9_Key_Light" },
        {"f10", "F10_Key_Light" },
        {"f11", "F11_Key_Light" },
        {"f12", "F12_Key_Light" },
        {"a", "A_Key_Light" },
        {"b", "B_Key_Light" },
        {"c", "C_Key_Light" },
        {"d", "D_Key_Light" },
        {"e", "E_Key_Light" },
        {"f", "F_Key_Light" },
        {"g", "G_Key_Light" },
        {"h", "H_Key_Light" },
        {"i", "I_Key_Light" },
        {"j", "J_Key_Light" },
        {"k", "K_Key_Light" },
        {"l", "L_Key_Light" },
        {"m", "M_Key_Light" },
        {"n", "N_Key_Light" },
        {"o", "O_Key_Light" },
        {"p", "P_Key_Light" },
        {"q", "Q_Key_Light" },
        {"r", "R_Key_Light" },
        {"s", "S_Key_Light" },
        {"t", "T_Key_Light" },
        {"u", "U_Key_Light" },
        {"v", "V_Key_Light" },
        {"w", "W_Key_Light" },
        {"x", "X_Key_Light" },
        {"y", "Y_Key_Light" },
        {"z", "Z_Key_Light" },
        {"alt", "Alt_Key_Light" },
        {"shift", "Shift_Key_Light" },
        {"ctrl", "Ctrl_Key_Light" },
        {"space", "Space_Key_Light" },
        {"enter", "Enter_Alt_Key_Light" },
        {"tab", "Tab_Key_Light" },
        {"escape", "Esc_Key_Light" },
        {"backspace", "Backspace_Alt_Key_Light" },
        {"up", "Arrow_Up_Key_Light" },
        {"down", "Arrow_Down_Key_Light" },
        {"left", "Arrow_Left_Key_Light" },
        {"right", "Arrow_Right_Key_Light" },
        {"insert", "Insert_Key_Light" },
        {"delete", "Delete_Key_Light" },
        {"home", "Home_Key_Light" },
        {"end", "End_Key_Light" },
        {"page up", "Page_Up_Key_Light" },
        {"page down", "Page_Down_Key_Light" },
        {"minus", "Minus_Key_Light" },
        {"plus", "Plus_Key_Light" },
        {"plus tall", "Plus_Tall_Key_Light" },
        {"asterisk", "Asterisk_Key_Light" },
        {"slash", "Slash_Key_Light" },
        {"semicolon", "Semicolon_Key_Light" },
        {"quote", "Quote_Key_Light" },
        {"bracket left", "Bracket_Left_Key_Light" },
        {"bracket right", "Bracket_Right_Key_Light" },
        {"mark left", "Mark_Left_Key_Light" },
        {"mark right", "Mark_Right_Key_Light" },
        {"tilda", "Tilda_Key_Light" },
        {"command", "Command_Key_Light" },
        {"windows", "Win_Key_Light" },
        {"caps lock", "Caps_Lock_Key_Light" },
        {"num lock", "Num_Lock_Key_Light" },

        // Mouse
        { "left button", "Mouse_Left_Key_Light" },
        { "right button", "Mouse_Right_Key_Light" },
        { "middle button", "Mouse_Middle_Key_Light" },
        { "mouse", "Mouse_Simple_Key_Light" },

        // Xbox controller
        { "buttonsouth", "XboxSeriesX_A" },
        { "buttonnorth", "XboxSeriesX_Y" },
        { "buttoneast", "XboxSeriesX_B" },
        { "buttonwest", "XboxSeriesX_X" },
        { "leftshoulder", "XboxSeriesX_LB" },
        { "rightshoulder", "XboxSeriesX_RB" },
        { "lefttrigger", "XboxSeriesX_LT" },
        { "righttrigger", "XboxSeriesX_RT" },
        { "leftstickpress", "XboxSeriesX_Left_Stick_Click" },
        { "rightstickpress", "XboxSeriesX_Right_Stick_Click" },
        { "leftstick", "XboxSeriesX_Left_Stick" },
        { "rightstick", "XboxSeriesX_Right_Stick" },
        { "dpadup", "XboxSeriesX_Dpad_Up" },
        { "dpaddown", "XboxSeriesX_Dpad_Down" },
        { "dpadleft", "XboxSeriesX_Dpad_Left" },
        { "dpadright", "XboxSeriesX_Dpad_Right" },
        { "menu", "XboxSeriesX_Menu" },
        { "view", "XboxSeriesX_View" },
        { "share", "XboxSeriesX_Share" },
        { "controller", "XboxSeriesX_Diagram_Simple" }
    };
}